object Version {
    const val androidXCore = "1.8.0"
    const val appcompat = "1.4.1"
    const val junit = "4.13.2"
    const val junitTestExt = "1.1.3"
    const val espresso = "3.4.0"
    const val material = "1.5.0"
    const val koinVersion = "3.4.2"
    const val retrofit = "2.9.0"
    const val okHttp = "4.1.0"
    const val androidktxCore= "1.9.0"
    const val kotlinVersion = "1.8.20"
    const val compose = "1.4.2"
    const val composeConstraintLayout = "1.0.1"
    const val kotlinCompilerVersion = "1.6.21"
    const val navVersion = "2.6.0"
    const val swipeRefreshLayout = "1.1.0"
    const val location = "21.0.1"
    const val maps = "18.1.0"
    const val permission = "0.30.1"
}